/* ============================================================================
 * build.js  —  Chinese Test Generator build step
 * ----------------------------------------------------------------------------
 * Produces two things from the source student player, with NO framework:
 *   1. dist/player.html            — a single self-contained student player
 *                                    (all CSS + JS inlined). Works offline as
 *                                    one file; opens a file picker if no test
 *                                    is embedded.
 *   2. js/generated/player-template.js — the same HTML as a JS string
 *                                    (window.CTG.PLAYER_TEMPLATE) so the
 *                                    teacher app can export a standalone test
 *                                    with the questions embedded, entirely in
 *                                    the browser.
 * Also regenerates:
 *   3. sample/sample-test.json     — a ready-made test from the template bank.
 *   4. dist/demo-test.html         — that sample embedded in the player, so you
 *                                    can double-click one file to try the flow.
 *
 * Run:  node tools/build.js   (also runnable via  npm run build)
 * ==========================================================================*/
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const p = (...a) => path.join(ROOT, ...a);
const read = f => fs.readFileSync(p(f), 'utf8');

function inlineHtml(htmlPath) {
  let html = read(htmlPath);
  // inline stylesheets
  html = html.replace(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g, (m, href) => {
    if (/^https?:/.test(href)) return m; // leave CDN links (none expected)
    return '<style>\n' + read(href) + '\n</style>';
  });
  // inline local scripts (but keep the empty embedded-test placeholder script)
  html = html.replace(/<script src="([^"]+)"><\/script>/g, (m, src) => {
    const js = read(src).replace(/<\/script>/g, '<\\/script>');
    return '<script>\n' + js + '\n</script>';
  });
  return html;
}

function ensureDir(d) { fs.mkdirSync(p(d), { recursive: true }); }

// ---- 1 & 2: self-contained player ----------------------------------------
const player = inlineHtml('student.html');
ensureDir('dist');
fs.writeFileSync(p('dist', 'player.html'), player);

ensureDir('js/generated');
const tpl = 'window.CTG = window.CTG || {};\n' +
  '/* Auto-generated by tools/build.js — do not edit by hand. */\n' +
  'window.CTG.PLAYER_TEMPLATE = ' + JSON.stringify(player) + ';\n';
fs.writeFileSync(p('js', 'generated', 'player-template.js'), tpl);

// ---- 3: sample test from the template bank --------------------------------
global.window = global;
global.XLSX = require(p('js', 'vendor', 'xlsx.full.min.js'));
['schema', 'excel-import', 'question-bank', 'test-generator', 'scoring', 'pinyin', 'storage', 'lms-adapter']
  .forEach(f => require(p('js', 'core', f + '.js')));
const CTG = global.CTG;

const buf = fs.readFileSync(p('templates', 'chinese-test-template.xlsx'));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
const { bank, report } = CTG.excel.parseWorkbook(ab);
if (!report.ok) { console.error('Template has errors, aborting sample generation'); process.exit(1); }

const settings = CTG.generator.defaultSettings();
settings.title = 'Sample Chinese Test (Units 1–4)';
settings.pinyinDefaultOn = false;
settings.allowPinyinToggle = true;
const { test } = CTG.generator.generate(bank, settings);
ensureDir('sample');
fs.writeFileSync(p('sample', 'sample-test.json'), JSON.stringify(test, null, 2));

// ---- 4: demo standalone (sample embedded) ---------------------------------
const json = JSON.stringify(test).replace(/</g, '\\u003c');
const demo = player.replace('/*__EMBEDDED_TEST__*/', 'window.__EMBEDDED_TEST__ = ' + json + ';');
fs.writeFileSync(p('dist', 'demo-test.html'), demo);

console.log('Build complete:');
console.log('  dist/player.html            (' + (player.length / 1024).toFixed(0) + ' KB, self-contained player)');
console.log('  js/generated/player-template.js');
console.log('  sample/sample-test.json     (' + test.maxPoints + ' points)');
console.log('  dist/demo-test.html         (sample embedded — double-click to try)');
